<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3f9d785ca8c96349e2bd5d74f31af576
{
    public static $prefixLengthsPsr4 = array (
        'S' =>
        array (
            'Shopimind\\SdkShopimind\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Shopimind\\SdkShopimind\\' =>
        array (
            0 => __DIR__ . '/..' . '/shopimind/sdk-shopimind/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'T' =>
        array (
            'Thelia\\Composer' =>
            array (
                0 => __DIR__ . '/..' . '/thelia/installer/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3f9d785ca8c96349e2bd5d74f31af576::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3f9d785ca8c96349e2bd5d74f31af576::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit3f9d785ca8c96349e2bd5d74f31af576::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit3f9d785ca8c96349e2bd5d74f31af576::$classMap;

        }, null, ClassLoader::class);
    }
}
