<?php return array(
    'root' => array(
        'name' => 'thelia/shopimind-module',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '78312ce3f339ca7d308adba04807f3430551ffdb',
        'type' => 'thelia-module',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'shopimind/sdk-shopimind' => array(
            'pretty_version' => 'V2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'edda35c9df9c7725d233b5e66214f6cf89011e8f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../shopimind/sdk-shopimind',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'thelia/installer' => array(
            'pretty_version' => '1.5',
            'version' => '1.5.0.0',
            'reference' => '30b7a084e64bd3a4ffb290fa6d9bf096b64b2b56',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../thelia/installer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'thelia/shopimind-module' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '78312ce3f339ca7d308adba04807f3430551ffdb',
            'type' => 'thelia-module',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
