<?php

/*
 * This file is part of the Thelia package.
 * http://www.thelia.net
 *
 * (c) OpenStudio <info@thelia.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    'Configuration of ShopiMind module' => 'Configuration of ShopiMind module',
    'API login' => 'API login',
    'API password' => 'API password',
    'Cache workaround' => 'Cache workaround',
    'Enable this mode if you are using a full page cache system.' => 'Enable this mode if you are using a full page cache system.',
    'Generate nominative vouchers?' => 'Generate nominative vouchers?',
    'Must ShopiMind vouchers be associated with your customers\' accounts (this means that your customer must be logged in to use it) ?' => 'Must ShopiMind vouchers be associated with your customers\' accounts (this means that your customer must be logged in to use it) ?',
    'Vouchers can be combined with other codes ?' => 'Vouchers can be combined with other codes ?',
    'Should vouchers generated by ShopiMind be combined with other promotional codes ?' => 'Should vouchers generated by ShopiMind be combined with other promotional codes ?',
    'Deactivate out-of-stock products ?' => 'Deactivate out-of-stock products ?',
    'Would you like to define out-of-stock products as desactivated ?' => 'Would you like to define out-of-stock products as desactivated ?',
    'Product image format to use in my emails' => 'Product image format to use in my emails',
    'This is the image format that will be used in your product recalls and recommendations.' => 'This is the image format that will be used in your product recalls and recommendations.',
    'Synchronize your newsletter subscribers ?' => 'Synchronize your newsletter subscribers ?',
    'If you have a newsletter registration form on your store, we can retrieve emails from a dedicated mailing list.' => 'If you have a newsletter registration form on your store, we can retrieve emails from a dedicated mailing list.',
    'Activate the tag script of Shopimind ?' => 'Activate the tag script of Shopimind ?',
    'Changes saved successfully.' => 'Changes saved successfully.',
    'Your module is not connected.' => 'Your module is not connected.',
    'Activate logs ?' => 'Activate logs ?',
    'Enabling logs allows for the recording of system or application events, providing a record that can be used for troubleshooting.' => 'Enabling logs allows for the recording of system or application events, providing a record that can be used for troubleshooting.',
    'Does the synchronization of your data have to be done in real time ?' => 'Does the synchronization of your data have to be done in real time ?',
    'Use real-time synchronization' => 'Use real-time synchronization',
    'Module connected to Shopimind.' => 'Module connected to Shopimind.',
    'You must select at least one status.' => 'You must select at least one status.',
    'Module not connected to Shopimind.' => 'Module not connected to Shopimind.',
    'Confirmed order statuses' => 'Confirmed order statuses',
    'Select order statuses to be considered as confirmed' => 'Select order statuses to be considered as confirmed',
];
