<?php

/*
 * This file is part of the Thelia package.
 * http://www.thelia.net
 *
 * (c) OpenStudio <info@thelia.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    'Configuration of ShopiMind module' => 'Configuration of ShopiMind module',
    'API login' => 'API login',
    'API password' => 'API password',
    'Cache workaround' => 'Cache workaround',
    'Enable this mode if you are using a full page cache system.' => 'Enable this mode if you are using a full page cache system.',
    'Generate nominative vouchers?' => 'Generate nominative vouchers?',
    'Must ShopiMind vouchers be associated with your customers\' accounts (this means that your customer must be logged in to use it) ?' => 'Must ShopiMind vouchers be associated with your customers\' accounts (this means that your customer must be logged in to use it) ?',
    'Vouchers can be combined with other codes ?' => 'Vouchers can be combined with other codes ?',
    'Should vouchers generated by ShopiMind be combined with other promotional codes ?' => 'Should vouchers generated by ShopiMind be combined with other promotional codes ?',
    'Deactivate out-of-stock products ?' => 'Deactivate out-of-stock products ?',
    'Would you like to define out-of-stock products as desactivated ?' => 'Would you like to define out-of-stock products as desactivated ?',
    'Product image format to use in my emails' => 'Product image format to use in my emails',
    'This is the image format that will be used in your product recalls and recommendations.' => 'This is the image format that will be used in your product recalls and recommendations.',
    'Synchronize your newsletter subscribers ?' => 'Synchronize your newsletter subscribers ?',
    'If you have a newsletter registration form on your store, we can retrieve emails from a dedicated mailing list.' => 'If you have a newsletter registration form on your store, we can retrieve emails from a dedicated mailing list.',
    'Activate the tag script of ShopiMind ?' => 'Activate the tag script of ShopiMind ?',
    'Hide the tag on checkout pages ?' => 'Hide the tag on checkout pages ?',
    'The ShopiMind tag is not injected on the checkout pages.' => 'The ShopiMind tag is not injected on the checkout pages.',
    'Cache workaround ?' => 'Cache workaround ?',
    'Customer and cart data are loaded after the page, so that a page cache never shows them to another visitor.' => 'Customer and cart data are loaded after the page, so that a page cache never shows them to another visitor.',
    'Changes saved successfully.' => 'Changes saved successfully.',
    'Your module is not connected.' => 'Your module is not connected.',
    'ShopiMind has not received the installed version of the module yet. Save the configuration to send it.' => 'ShopiMind has not received the installed version of the module yet. Save the configuration to send it.',
    'Does the synchronization of your data have to be done in real time ?' => 'Does the synchronization of your data have to be done in real time ?',
    'Use real-time synchronization' => 'Use real-time synchronization',
    'Module connected to ShopiMind.' => 'Module connected to ShopiMind.',
    'You must select at least one status.' => 'You must select at least one status.',
    'Module not connected to ShopiMind.' => 'Module not connected to ShopiMind.',
    'Confirmed order statuses' => 'Confirmed order statuses',
    'Select order statuses to be considered as confirmed' => 'Select order statuses to be considered as confirmed',
    'The configuration was not saved: %error' => 'The configuration was not saved: %error',
    'The module could not be connected to ShopiMind. Check the API ID and password, then save again.' => 'The module could not be connected to ShopiMind. Check the API ID and password, then save again.',
    'Developer / Debug' => 'Developer / Debug',
    'Log level' => 'Log level',
    'Off' => 'Off',
    'Errors only' => 'Errors only',
    'Info (recommended)' => 'Info (recommended)',
    'Debug (verbose)' => 'Debug (verbose)',
    'Logs are written to the shopimind.log file. Use Debug only for a diagnosis.' => 'Logs are written to the shopimind.log file. Use Debug only for a diagnosis.',
    'ShopiMind API URL' => 'ShopiMind API URL',
    'Tracking script URL' => 'Tracking script URL',
    'Used only when the log level is Debug. Leave empty to use the default URL.' => 'Used only when the log level is Debug. Leave empty to use the default URL.',
    'URL in use:' => 'URL in use:',
    'Enter a full URL starting with https:// or http://, without login, query string or anchor.' => 'Enter a full URL starting with https:// or http://, without login, query string or anchor.',
];
