<?php

/*
 * This file is part of the Thelia package.
 * http://www.thelia.net
 *
 * (c) OpenStudio <info@thelia.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    'Configuration of ShopiMind module' => 'Configuration du module Shopimind',
    'API login' => 'Identifiant de l\'API',
    'API password' => 'Mot de passe API',
    'Cache workaround' => 'Solution de contournement du cache',
    'Enable this mode if you are using a full page cache system.' => 'Activez ce mode si vous utilisez un système de cache pleine page.',
    'Generate nominative vouchers?' => 'Générer des codes de réduction nominatifs',
    'Must ShopiMind vouchers be associated with your customers\' accounts (this means that your customer must be logged in to use it) ?' => 'Les codes de réduction générés par ShopiMind doivent-ils être associés aux comptes de vos clients (cela implique que votre client doit être connecté pour l\'utiliser)',
    'Vouchers can be combined with other codes ?' => 'Codes de réduction cumulables avec d\'autres codes ?',
    'Should vouchers generated by ShopiMind be combined with other promotional codes ?' => 'Les codes de réduction générés par ShopiMind doivent-ils être cumulables avec les autres codes promotionnels ?',
    'Deactivate out-of-stock products ?' => 'Désactiver les produits en rupture de stock ?',
    'Would you like to define out-of-stock products as desactivated ?' => 'Souhaitez-vous définir les produits en rupture de stock comme désactivés ?',
    'Product image format to use in my emails' => 'Format d\'image produit à utiliser dans mes Emails',
    'This is the image format that will be used in your product recalls and recommendations.' => 'Il s\'agit du format d\'image qui sera utilisé dans vos rappels et recommandations de produits.',
    'Synchronize your newsletter subscribers ?' => 'Synchroniser vos abonnés newsletter ?',
    'If you have a newsletter registration form on your store, we can retrieve emails from a dedicated mailing list.' => 'Si vous disposez d\'un formulaire d\'inscription à votre newsletter sur votre boutique, nous pouvons récupérer les e-mails dans une liste d\'envoi dédiée.',
    'Activate the tag script of Shopimind ?' => 'Activer le script tag de Shopimind ?',
    'Validate' => 'Valider',
    'Changes saved successfully.' => 'Modifications enregistrées avec succès.',
    'Your module is not connected.' => 'Votre module n\'est pas connecté.',
    'Activate logs ?' => 'Activer les logs ?',
    'Enabling logs allows for the recording of system or application events, providing a record that can be used for troubleshooting.' => 'Activer les journaux permet d\'enregistrer les événements du système ou de l\'application, fournissant un enregistrement pouvant être utilisé à des fins de dépannage',
    'Does the synchronization of your data have to be done in real time ?' => 'La synchronisation de vos données doit-elle se faire en temps réel ?',
    'Use real-time synchronization' => 'Utiliser la synchronisation en temps réel',
];
